language: python

python:
  - '3.9'

services:
  - docker

jobs:
  include:
    - stage: reproduce_issue
      env: K8S=v1.25.8
      before_script:
        - echo "Setting up test environment..."
      script:
        - echo "Running test script..."
        - # Add the commands to reproduce the port forwarding issue here.
